name: Build
on: push
jobs:
  docker-build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: docker build --output=./output .
      - name: Update Nightly
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload nightly output/* -R ${{github.repository}} --clobber
